### ISSUE TITLE
仿真无法运行

### ISSUE THREAD

**Issue by fan-ziqi** [MiRoboticsLab/cyberdog_simulator#1]
仿真报错，重新启动后无法运行

<img width="504" alt="5be826a5f631e74f81c418f666793e9" src="https://github.com/MiRoboticsLab/cyberdog_simulator/assets/62320343/61752c34-58ef-4622-b3a8-85c3ed96e1be">
<img width="851" alt="e73cba2c910139e0c9e932cd0da81b6" src="https://github.com/MiRoboticsLab/cyberdog_simulator/assets/62320343/16ad5d5e-3fa3-4550-aece-88ce4a2ec78c">

**Comment by 562986047** [comment]
ODE Message 3: LCP internal error, s <= 0
该报错大多由于机器人趴在地上时接触过多导致的求解器错误，但对仿真器的运行无太大的影响
启动过gazebo后重启出错可能是由于gazebo没有彻底关闭导致，可尝试运行
`killall -9 gazebo & killall -9 gzserver & killall -9 gzclient`
杀死所有gazebo进程后重新启动
